name: kubernetes deployment
on: [push]
jobs:
    build-frontend:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
            - run: |
                cd frontend &&
                npm install &&
                npm run build &&
                ls -la






