name: kubernetes deployment
on: [push]
jobs:
    build-frontend:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
            - run: |
                cd frontend &&
                npm install &&
                npm run build &&
                ls -la
    upload-s3: 
        runs-on: ubuntu-latest
        container: amazon/aws-cli:latest
        steps:
            steps:
            - name: Checkout repository
            uses: actions/checkout@v2
    
            - name: Install AWS CLI
            run: |
                    sudo apt-get update
                    sudo apt-get install -y awscli
        
            - name: Upload to S3
            run: |
                    aws s3 sync ./your-local-directory s3://your-bucket-name --delete
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        
            
