name: kubernetes deployment
on: [push]
jobs:
    build-frontend:
        runs-on: ubuntu-latest
        container: node:latest
        steps:
            - run: |
                cd frontend &&
                npm install &&
                npm run build &&
                ls -la






